
export const administrativePosts = {
  // niassa

  Chimbonila: ["Chimbonila", "Lione"],
  Cuamba: ["Cuamba", "Etatara", "Lurio"],
  Lago: ["Cobue", "Lunho", "Maniamba", "Metangula"],
  Lichinga: ["Chimbonila", "Lione", "Lichinga", "Meponda"],
  Majune: ["Majune", "Muaquia", "Nairrubi"],
  Mandimba: ["Mitande", "Mitande"],
  Marrupa: ["Marangira", "Murrupa", "Nungo"],
  Maúa: ["Maua", "Maiaca"],
  Mavago: ["M'Sawizw", "Mavago"],
  Mecanhelas: ["Chiuta", "Mecanhelas"],
  Mecula: ["Matondovela", "Mecula"],
  Metarica: ["Metarica", "Mucumua"],
  Muembe: ["Chiconono", "Muembe"],
  "N'gauma": ["Itepela", "Massangulo"],
  Nipepe: ["Muipite", "Nipepe"],
  Sanga: ["Lussimbeze", "Macaloge", "Matchedje", "Sanga"],

  // cabo delgado
  Ancuabe: ["Ancuabe", "Metoro", "Meza"],
  Balama: ["Balama", "Impiri", "Kwekwe", "Mavala"],
  Chiúre: ["Chiure", "Chiure Velho", "Katapua", "Mazeze", "Namogelia", "Ocua"],
  Ibo: ["Ibo", "Quirimba"],
  Macomia: ["Macomia", "Chai", "Mucojo", "Quiterajo"],
  Mecúfi: ["Mecufi", "Murrebue"],
  Meluco: ["Meluco", "Muaguide"],
  "Mocímboa da Praia": ["Mocimboa da Praia", "Diaca", "Mbau"],
  Montepuez: ["Montepuez", "Mapupulo", "Mirate", "Nairoto", "Namanhumir"],
  Mueda: ["Mueda", "Chapa", "Imbuho", "Negomano", "N'gapa"],
  Muidumbe: ["Muidumbe", "Chitunda", "Miteda"],
  Namuno: ["Namuno", "Hucula", "Machoca", "Meloco", "Ncumpe", "Luli"],
  Nangade: ["Nangade", "Ntamba"],
  Palma: ["Palma", "Olumbe", "Pundanhar", "Quionga"],
  Pemba: ["Pemba"],
  "Pemba-Metuge": ["Metuge", "Mieze"],
  Quissanga: ["Quissange", "Bilibiza", "Mahate"],

  // nampula
  Angoche: ["Angoche", "Aube", "Namaponda", "Boila-Nametoria"],
  Eráti: ["Namapa", "Alua", "Namiroa"],
  "Ilha de Moçambique": ["Ilha de Moçambique", "Lumbo"],
  Lalaua: ["Lalaua", "Meti"],
  Larde: ["Larde", "Mucuali"],
  Liúpo: ["Liúpo", "Quinga"],
  Malema: ["Malema", "Chihulo", "Mutuali"],
  Meconta: ["Meconta", "Corrane", "Namialo", "7 de Abril"],
  Mecubúri: ["Mecubúri", "Milhana", "Muite", "Namina"],
  Memba: ["Memba", "Chipene", "Lurio", "Mazue"],
  Mogincual: ["Mogincual", "Quinga", "Chunga", "Quixaxe", "Liupo"],
  Mogovolas: ["Nametil", "Calipo", "Ilute", "Muatua", "Nanhupo"],
  Moma: ["Macone", "Chalaua", "Larde", "Mucuali"],
  Monapo: ["Monapo", "Itoculo", "Netia"],
  Mossuril: ["Mossuril", "Lunga", "Matibane"],
  Muecate: ["Muecate", "Imala", "Muculuone"],
  Murrupula: ["Murrupula", "Chinga", "Nehessine"],
  "Nacala Porto": ["Maiaia", "Mutiva", "Muanona"],
  "Nacala-a-Velha": ["Nacala-a-Velha", "Covo"],
  Nampula: [
    "Muatala",
    "Muhala",
    "Namikopo",
    "Napipine",
    "Natikire",
    "Urbano Central",
  ],
  Nacarôa: ["Nacarôa", "Intete", "Saua-Saua"],
  Rapale: ["Rapale", "Anchilo", "Mutivaze", "Namaita"],
  Ribaué: ["Ribaué", "Kunle", "Iapala"],

  // zambezia
  "Alto Molócuè": ["Alto Molócuè", "Nauela"],
  Chinde: ["Chinde", "Luabo", "Micaune"],
  Derre: ["Derre", "Machimbo", "Guerissa"],
  Gilé: ["Gilé", "Alto Lingonha"],
  Gurué: ["Gurué", "Lioma", "Nepuagiua"],
  Ile: ["Ile", "Mulevala", "Socone"],
  Inhassunge: ["Mucupia", "Gonhane"],
  Lugela: ["Lugela", "Tacuane", "Munhamade", "Muabanama"],
  "Maganja da Costa": ["Maganja da Costa", "Bojone", "Mocubela", "Nante"],
  Milange: ["Milange", "Majaua", "Molumbo", "Mongue"],
  Mocuba: ["Mocuba", "Mugeba", "Namajavira"],
  Mopeia: ["Mopeia", "Campo"],
  Morrumbala: ["Morrumbala", "Chire", "Megaza"],
  Namacurra: ["Namacurra", "Mucuse", "Namarroi", "Regone"],
  Nicoadala: ["Nicoadala", "Maquival"],
  Pebane: ["Pebane", "Mulela Mualama", "Naburi"],
  Quelimane: ["Quelimane"],

  // tete
  Angónia: ["Domue", "Ulongoe"],
  "Cahora-Bassa": ["Chitholo", "Chitima", "Songo"],
  Changara: ["Chioco", "Mavara", "Luenha"],
  Chifunde: ["Chifunde", "Mualadzi", "N'Sadzo"],
  Chiuta: ["Kazula", "Mange"],
  Dôa: ["Chueza", "Dôa"],
  Macanga: ["Chidzolomondo", "Furancungo"],
  Magoé: ["Chinthopo", "Mpeheende", "Mukumbura"],
  Marara: ["Baroma", "Chococoma", "Kachembe", "Mufa-Conde"],
  Marávia: ["Chiputo", "Fingoe", "Malowera", "Chepera"],
  Moatize: ["Moatize", "Kambulatsitsi", "Zombue"],
  Mutarara: ["Chare", "Inhangoma", "Nhamayabué"],
  Tete: ["Tete"],
  Tsangano: ["Ntengo-Wambalame", "Tsangano"],
  Zumbo: ["Muze", "Zambue", "Zumbo"],

  // sofala
  Beira: ["Central", "Munhava", "Inhamizua", "Manga Loforte", "Nhangau"],
  Búzi: ["Búzi", "Estaquinha", "Nova-Sofala"],
  Caia: ["Caia", "Murraça", "Sena"],
  Chemba: ["Chemba", "Chiramba", "Mulima"],
  Cheringoma: ["Inhaminga", "Inhamitanga"],
  Chibabava: ["Chibabava", "Goonda", "Muxungue"],
  Dondo: ["Dondo", "Mafambisse"],
  Gorongosa: ["Gorongosa", "Nhamadzi", "Vanduzi"],
  Machanga: ["Divinhe", "Machanga"],
  Maringué: ["Canxixe", "Maringué", "Subui"],
  Marromeu: ["Chupanga", "Marromeu"],
  Muanza: ["Galinha", "Muanza"],
  Nhamatanda: ["Nhamatanda", "Tica"],

  // Manica

  Bárue: ["Catandica", "Choa", "Nhampassa"],
  Chimoio: ["Chimoio"],
  Gondola: ["Amatongas", "Cafumpe", "Gondola", "Inchope"],
  Guro: ["Guro", "Mandie", "Mungari", "Nhamassonge"],
  Macate: ["Macate", "Zembe"],
  Machaze: ["Machaze", "Save"],
  Macossa: ["Macossa", "Nguawala"],
  Manica: ["Manica", "Machipanda", "Messica", "Mavonde"],
  Mossurize: ["Espungabera", "Chiurairue", "Dacata"],
  Sussundenga: ["Sussundenga", "Dombe", "Muhoa", "Rotanda"],
  Tambara: ["Nhacolo", "Buzua", "Nhacafula"],
  Vanduzi: ["Matsinho"],

  // inhambane
  Funhalouro: ["Funhalouro", "Tome"],
  Govuro: ["Nova Mambone", "Save"],
  Homoíne: ["Homoíne", "Pembe"],
  Inhambane: ["Inhambane"],
  Inharrime: ["Inharrime", "Mucumbi"],
  Inhassoro: ["Inhassoro", "Bazaruto"],
  Jangamo: ["Jangamo", "Cumbana"],
  Mabote: ["Mabote", "Zimane", "Zinave"],
  Massinga: ["Massinga", "Chicomo"],
  Maxixe: ["Maxixe"],
  Morrumbene: ["Morrumbene", "Mocodoene"],
  Panda: ["Panda", "Mawayela", "Urrene"],
  Vilanculos: ["Vilanculos", "Mapinhane"],
  Zavala: ["Quissico", "Zandamela"],

  // gaza

  Bilene: [
    "Macia",
    "Chissano",
    "Mazivala",
    "Messano",
    "Praia de Bilene",
    "Macuane",
  ],
  Chibuto: [
    "Chibuto",
    "Alto Changane",
    "Chaimite",
    "Changanine",
    "Godide",
    "Malehice",
  ],
  Chicualacuala: ["Chicualacuala", "Mapai", "Pafuri"],
  Chigubo: ["Chigubo", "Ndindiza"],
  Chókwè: ["Chókwè", "Lionde", "Macarretane", "Xilembene"],
  Chongoene: ["Chongoene", "Mazucane", "Nguzene"],
  Guijá: ["Chivonguene", "Caniçado", "Mubanguene", "Nalazi"],
  Limpopo: ["Chissano", "Chicumbane", "Zonguene"],
  Mabalane: ["Mabalane", "Combomune", "Ntlavane"],
  Manjacaze: [
    "Mandlacaze",
    "Chalala",
    "Chibonzane",
    "Chidenguele",
    "Macuacua",
    "Mazucane",
    "Nguzene",
  ],
  Mapai: ["Mapai", "Machaila"],
  Massangena: ["Massangena", "Muvue"],
  Massingir: ["Massingir", "Mavodze", "Zulo"],
  "Xai-Xai": ["Chicumbane", "Chongoene", "Zonguene"],

  // maputo

  Boane: ["Boane", "Matola-Rio"],
  Magude: ["Magude", "Mapulanguene", "Motaze", "Mahel", "Panjane"],
  Manhiça: [
    "Manhiça",
    "Calanga",
    "Ilha de Josina Machel",
    "Maluana",
    "Xinavane",
    "3 de Fevereiro",
  ],
  Marracuene: ["Marracuene", "Machubo", ""],
  Matola: ["Matola", "Infulene", "Machava"],
  Matutuíne: ["Missevene", "Catembe", "Catuane", "Machangulo", "Zitundo"],
  Moamba: ["Moamba", "Pessene", "Ressano Garcia", "Sabie"],
  Namaacha: ["Namaacha", "Changalane"],

  // maputo cidade
  KaMpfumu: [
    "Alto Maé",
    "Bairro Central",
    "Coop",
    "Malhangalene",
    "Polana-Cimento",
    "Sommerschield",
  ],

  Nlhamankulu: [
    "Aeroporto",
    "Chamanculo",
    "Malanga",
    "Minkadjuine",
    "Munhuana",
    "Unidade 7",
    "Xipamanine",
  ],

  KaMaxakeni: ["Mafalala", "Maxaquene", "Polana Caniço", "Urbanização"],

  KaMavota: [
    "3 de Fevereiro",
    "Albazine",
    "Costa do Sol",
    "F.P.L.M.",
    "Ferroviário",
    "Hulene",
    "Laulane",
    "Mahotas",
    "Mavalane",
  ],

  KaMubukwana: [
    "25 de Junho A",
    "25 de Junho B",
    "Bagamoyo",
    "George Dimitrov",
    "Inhagóia",
    "Jardim",
    "Luis Cabral",
    "Magoanine",
    "Malhazine",
    "Nsalene",
    "Zimpeto",
  ],

  KaTembe: ["Inguide", "Incassane", "Guachene", "Chali", "Chamissava"],

  KaNyaka: [
    "Ribzwene", 
    "Inguane",
    "Nhanquene",
  ]
};